WebApp_MVC_Assignment4/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp_MVC_Assignment4.Models;
using WebApp_MVC_Assignment4.Models.Services;
using WebApp_MVC_Assignment4.Models.ViewModels;

namespace WebApp_MVC_Assignment4.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService _cityService;
        private readonly IPeopleService _peopleService;

        /*public CityController(ICityService cityService)
        {
            _cityService = cityService;
        }*/

        public CityController(ICityService cityService, IPeopleService peopleService)
        {
            _cityService = cityService;
            _peopleService = peopleService;
        }

        // GET: CityController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CityController/City
        public ActionResult City()
        {
            CreateCityViewModel ctyVM = new CreateCityViewModel();
            ctyVM.CityList=_cityService.All();
            return View(ctyVM);
        }

        // GET: CityController/Details/5
        [HttpGet]
        public ActionResult CityDetails(int id)
        {
            CreateCityViewModel ctyVm = new CreateCityViewModel();
            City cityDetails = _cityService.FindBy(id);
            ctyVm.CityName = cityDetails.CityName;
            ctyVm.States = cityDetails.States;
            ctyVm.PersonInCity = _cityService.FindAllPerson(id);
            return View(ctyVm);
        }

        // GET: CityController/Create
        public ActionResult Create()
        {
            PeopleViewModel pplVM = _peopleService.All();
            CreateCityViewModel cityVM = new CreateCityViewModel();
            cityVM.PersonInCity = pplVM.AllPeople;
            return View(cityVM);
        }

        // POST: CityController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCityViewModel createCity)
        {
            City city = null;

            if (ModelState.IsValid)
            {
                
                city = _cityService.Add(createCity);
                
                if (city == null)
                {
                    ModelState.AddModelError("msg", "Database Problem");
                    return View(createCity);
                }

                return RedirectToAction(nameof(City));
            }
            else
            {
                return View(createCity);
            }
                
        } 

        // GET: CityController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            PeopleViewModel pplVM = _peopleService.All();
            CreateCityViewModel cityVM = new CreateCityViewModel();
            City editCity = _cityService.FindBy(id);

            cityVM.States = editCity.States;
            cityVM.CityName = editCity.CityName;
            cityVM.PersonInCity = pplVM.AllPeople;
            cityVM.updateCityID = id;
            
            return View("Edit", cityVM);
        }

        // POST: CityController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateCityViewModel updCity)
        { 
            _cityService.Edit(updCity.updateCityID, updCity);

            return RedirectToAction(nameof(City));
        }

        // GET: CityController/Delete/5
        public ActionResult Delete(int id)
        {
            _cityService.Remove(id);
            return RedirectToAction(nameof(City));
        }

        // POST: CityController/Delete/5
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            _cityService.Remove(id);
            _cityService.All();
            return RedirectToAction(nameof(Create));
        }*/
    }
}

WebApp_MVC_Assignment4/Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp_MVC_Assignment4.Models;
using WebApp_MVC_Assignment4.Models.Services;
using WebApp_MVC_Assignment4.Models.ViewModels;

namespace WebApp_MVC_Assignment4.Controllers
{
    public class CountryController : Controller
    {
        private readonly ICityService _cityService;
        private readonly ICountryService _countryService;
                
        public CountryController(ICityService cityService, ICountryService countryService)
        {
            _cityService = cityService;
            _countryService = countryService;
        }

        // GET: CountryController
        public ActionResult ShowCountry()
        {
            /*CreateCountryViewModel ctyVM = new CreateCountryViewModel();

            Country cty = new Country();

            cty.CountryName = "Default Country";
            cty.CountryId = 0;

            List<Country> countryList = new List<Country>();
            countryList.Add(cty);

            ctyVM.CountryList = countryList;*/

            CreateCountryViewModel ctyVM = new CreateCountryViewModel();
            ctyVM.CountryList = _countryService.All();
            return View(ctyVM);
            //return View("ShowCountry",ctyVM);
        }

        // GET: CountryController/Details/5
        public ActionResult CountryDetails(int id)
        {
            CreateCountryViewModel ctyVM = new CreateCountryViewModel();
            Country  ctyDetails=_countryService.FindBy(id);

            ctyVM.CountryId = ctyDetails.CountryId;
            ctyVM.CountryName = ctyDetails.CountryName;
            //ctyVM.CityList = _cityService.All(); //gives all the cities in the database and not for this particular country 
            ctyVM.CityList= _countryService.FindAllCity(id); //gives all the cities in the database for this particular country 
            return View(ctyVM);
        }

        // GET: CountryController/Create
        public ActionResult CreateCountry()
        {
            CreateCountryViewModel ctyVM = new CreateCountryViewModel();
            ctyVM.CityList=_cityService.All();
            return View(ctyVM);
        }

        // POST: CountryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCountry(CreateCountryViewModel ctyVM)
        {
            if (ModelState.IsValid)
            {
                Country country = _countryService.Add(ctyVM);

                if (country == null)
                {
                    ModelState.AddModelError("msg", "Database Problem");
                    return View(ctyVM);
                }

                return RedirectToAction(nameof(ShowCountry));
            }
            else
            {
                return View(ctyVM);
            }
        }

        // GET: CountryController/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            CreateCountryViewModel ctyVM = new CreateCountryViewModel();
            Country editCountry=  _countryService.FindBy(id);
            ctyVM.CountryName = editCountry.CountryName;
            ctyVM.CountryId = editCountry.CountryId;

            List<City> allCities = _cityService.All();
            ctyVM.CityList = allCities;

            return View("Edit",ctyVM);
        }

        // POST: CountryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreateCountryViewModel editCountry)
        {
            _countryService.Edit(editCountry.CountryId , editCountry);

            return RedirectToAction(nameof(ShowCountry));
        }

        // GET: CountryController/Delete/5
        public ActionResult Delete(int id)
        {
            _countryService.Remove(id);

            return RedirectToAction(nameof(ShowCountry));
        }

        // POST: CountryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(ShowCountry));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp_MVC_Assignment4/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using WebApp_MVC_Assignment4.Models;

namespace WebApp_MVC_Assignment4.Controllers
{
    public class PeopleController : Controller
    {
        private IPeopleService ps;
        public PeopleController(IPeopleService peopleService)
        {
            ps = peopleService;
        }

        private PeopleViewModel peopleViewModel;
       /* private readonly ILogger<PeopleController> _logger;

        public PeopleController(ILogger<PeopleController> logger)
        {
            _logger = logger;
        }*/

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Add_View_People()
        {

            if (peopleViewModel == null)
            {
                peopleViewModel = ps.All();
            }

            //peopleViewModel = ps.All();
            return View(peopleViewModel);
        }


        [HttpPost]
        public IActionResult Add_View_People(PeopleViewModel objModel)
        {
            CreatePersonViewModel createPersonModelView = new CreatePersonViewModel();
            if (objModel.AddPerson != null)
            {
                if (ModelState.IsValid)
                {                    
                    createPersonModelView = objModel.AddPerson;
                    peopleViewModel = null;
                    ps.Add(createPersonModelView);
                }
                else
                {
                    peopleViewModel.ModelErr = "Required fields are missing";
                }
            }

            if (objModel.Search != null)
            {
                peopleViewModel = ps.FindBy(objModel);
            }

            //return View("Add_View_People", peopleViewModel);
            return RedirectToAction(nameof(Add_View_People));
        }

        public IActionResult DeletePeople(int id)
        {
            ps.Remove(id);
            peopleViewModel = ps.All();
            return RedirectToAction(nameof(Add_View_People));
            //return View("Add_View_People", peopleViewModel);
        }
        public IActionResult EditPeople(int id)
        {
            Person person = new Person();

            //to be replaced by user input
            person.FirstName = "EditFName";
            person.LastName = "EditLName";
            person.PhoneNumber = "123456789";
            person.Address = "EditAddress";

            ps.Edit(id, person);
            peopleViewModel = ps.All();
            return RedirectToAction(nameof(Add_View_People));
        }

        /*AJAX related code*/
        [HttpGet]
        public IActionResult AddPerson()
        {
            return PartialView("_AddPerson");
        }
        
        [HttpPost]
        public IActionResult AddPerson(CreatePersonViewModel person)
        {
            Person newPerson = null;
            if (ModelState.IsValid)
            {
                newPerson = ps.Add(person);
                return PartialView("_PersonPV", newPerson);
            }
            Response.StatusCode = 400;
            return PartialView("_AddPerson", person);
        }

        [HttpGet]
        public IActionResult EditPerson(int id)
        {
            Person editPerson = ps.FindBy(id);

            /*
            CreatePersonViewModel modelPerson = new CreatePersonViewModel();
            modelPerson.FirstName = editPerson.FirstName;
            modelPerson.LastName = editPerson.LastName;
            modelPerson.PhoneNumber = editPerson.PhoneNumber;
            modelPerson.Address = editPerson.Address;*/

            return PartialView("_EditPerson", editPerson);
        }

        [HttpPost]
        public IActionResult EditPerson(Person person)
        {
            Person editedPerson = null;
            if (ModelState.IsValid)
            {
                editedPerson = ps.Edit(person.PersonID,person);
                return PartialView("_PersonPV", editedPerson);
            }

            Response.StatusCode = 400;
            return PartialView("_EditPerson", person);
        }

        public IActionResult RemovePerson(int id)
        {
            Person removedPerson = null;
            if (ps.Remove(id)) 
            {
                removedPerson = null;
            }

            return PartialView("_PersonPV", removedPerson);
        }

        [HttpPost]
        public IActionResult SearchPeople(PeopleViewModel objModel)
        {
            if (objModel.Search != null)
            {
                peopleViewModel = ps.FindBy(objModel);
            }
            else 
            {
                peopleViewModel = ps.All();
            }

            return PartialView("_SearchPeople", peopleViewModel);
        }
        /*AJAX related code*/

    }
}

WebApp_MVC_Assignment4/Views/Shared/_AddPerson.cshtml
@model CreatePersonViewModel

<div>
    <h3>Add Person</h3>
</div>

<br/>

<form asp-controller="People" asp-action="AddPerson" onsubmit="PostAddPersonForm(event, this)" >
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span class="text-danger" asp-validation-for="FirstName"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span class="text-danger" asp-validation-for="LastName"></span>

    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span class="text-danger" asp-validation-for="PhoneNumber"></span>

    </div>
    <div class="form-group">
        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span class="text-danger" asp-validation-for="Address"></span>

    </div>
    <input type="submit" value="Create Person" class="btn btn-outline-primary" />
</form>

WebApp_MVC_Assignment4/Views/Shared/_EditPerson.cshtml
@model Person

<form asp-controller="People" asp-action="EditPerson" onsubmit="PostEditPersonForm(event, this)">
       <div class="form-group">
            <input asp-for="PersonID" type="hidden" />
        </div>
       <div class="form-group">
           <label asp-for="FirstName"></label>
           <input asp-for="FirstName" class="form-control" />
           <span class="text-danger" asp-validation-for="FirstName"></span>

       </div>
       <div class="form-group">
           <label asp-for="LastName"></label>
           <input asp-for="LastName" class="form-control" />
           <span class="text-danger" asp-validation-for="LastName"></span>

       </div>
       <div class="form-group">
           <label asp-for="PhoneNumber"></label>
           <input asp-for="PhoneNumber" class="form-control" />
           <span class="text-danger" asp-validation-for="PhoneNumber"></span>

       </div>
       <div class="form-group">
           <label asp-for="Address"></label>
           <input asp-for="Address" class="form-control" />
           <span class="text-danger" asp-validation-for="Address"></span>

       </div>
        <input type="submit" value="OK" class="btn btn-outline-primary" />
</form>

WebApp_MVC_Assignment4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp_MVC_Assignment4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="People" asp-action="Add_View_People">Person Web App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="City">City</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="ShowCountry">Country</a>
                        </li>
                         
                    </ul>                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Shreya Sai
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/PersonUtility.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp_MVC_Assignment4/Views/Shared/_PersonPV.cshtml
@model Person
@*--Without AJAX
    <tr>
        <th scope="col">@Model.FirstName</th>
        <th scope="col">@Model.LastName</th>
        <th scope="col">@Model.PhoneNumber</th>
        <th scope="col">@Model.Address</th>
        <th scope="col">
            <a asp-controller="People" asp-action="DeletePeople" asp-route-id=@Model.PersonID class="btn btn-outline-danger">Remove</a>
        </th>
        <th scope="col">
            <a asp-controller="People" asp-action="EditPeople" asp-route-id=@Model.PersonID class="btn btn-outline-dark">Edit</a>
        </th>
    </tr>
*@

@if (Model != null)
{
  string rowid = "personRowID-" + Model.PersonID;
  <div id="@rowid">
    <div class="row">
        <div class="col">@Model.FirstName</div>
        <div class="col">@Model.LastName</div>
        <div class="col">@Model.PhoneNumber</div>
        <div class="col">@Model.Address</div>
        <div class="col">
             <button onclick="GetEditPersonForm('@Url.Action("EditPerson","People")','@Model.PersonID')" class="btn btn-outline-dark">Edit</button>
        </div>
        <div class="col">
            <button onclick="RemovePerson('@Url.Action("RemovePerson","People")','@Model.PersonID')" class="btn btn-outline-danger">Remove</button>
        </div>
    </div>
  </div> 
}

WebApp_MVC_Assignment4/Views/Shared/_SearchPeople.cshtml
@model PeopleViewModel

<div class="row">
    <div class="col">First Name</div>
    <div class="col">Last Name</div>
    <div class="col">Phone Number</div>
    <div class="col">Address</div>
    <div class="col"> </div>
    <div class="col"> </div>
</div>
@foreach (Person person in Model.AllPeople)
{
    string rowid = "personRowID-" + person.PersonID;
    <div id="@rowid">
        <div class="row">
            <div class="col">@person.FirstName</div>
            <div class="col">@person.LastName</div>
            <div class="col">@person.PhoneNumber</div>
            <div class="col">@person.Address</div>
            <div class="col">
                <button onclick="GetEditPersonForm('@Url.Action("EditPerson","People")','@person.PersonID')" class="btn btn-outline-dark">Edit</button>
            </div>
            <div class="col">
                <button onclick="RemovePerson('@Url.Action("RemovePerson","People")','@person.PersonID')" class="btn btn-outline-danger">Remove</button>
            </div>
        </div>
     </div>
 }